[book]
title = "Guide to Rustc Development"
author = "Rustc developers"
description = "A guide to developing rustc"

[build]
create-missing = false

[output.html]

[output.html.search]

[output.linkcheck]
follow-web-links = true
exclude = [ "crates\\.io", "gcc\\.godbolt\\.org", "youtube\\.com", "dl\\.acm\\.org" ]
cache-timeout = 172800
warning-policy = "error"
